import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeadingBar from "./components/HeadingBar";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Josefin_Sans } from "next/font/google"; 

// Load the Josefin Sans font at the module scope
const josefin = Josefin_Sans({
  weight: ['400', '700'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
});


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={josefin.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<HeadingBar />

<Navbar />

        {children}

<Footer />

      </body>
    </html>
  );
}
